package com.hx.dao;

import java.util.List;

import com.hx.domain.RequestOpLog;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface RequestOpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    int countByExample(RequestOpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    int deleteByExample(RequestOpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    int insert(RequestOpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    int insertSelective(RequestOpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    List<RequestOpLog> selectByExample(RequestOpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    RequestOpLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") RequestOpLog record, @Param("example") RequestOpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    int updateByExample(@Param("record") RequestOpLog record, @Param("example") RequestOpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    int updateByPrimaryKeySelective(RequestOpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_request_op_log
     *
     * @mbggenerated Wed Mar 18 11:11:09 CST 2015
     */
    int updateByPrimaryKey(RequestOpLog record);
}